export const SECTIONS_API_ENDPOINT = 'https://express.oliver-wilson-dev.now.sh/sections';
export const LIGHT_THEME = 'LIGHT_THEME';
export const DARK_THEME = 'DARK_THEME';
export const COOKIE_POLICY = 'COOKIE_POLICY';
export const COOKIE_POLICY_ACCEPTED = 'COOKIE_POLICY_ACCEPTED';


// ACTION TYPES
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const TOGGLE_SHOW_SIDE_NAV = 'TOGGLE_SHOW_SIDE_NAV';
export const FETCH_CONTENT = 'FETCH_CONTENT';
export const LEARN_MORE_CLICKED = 'LEARN_MORE_CLICKED';
export const FETCH_CONTENT_FAILURE = 'FETCH_CONTENT_FAILURE';
export const USER_ACCEPTED_COOKIE_POLICY = 'USER_ACCEPTED_COOKIE_POLICY';
